### ISSUE TITLE
Game seemingly freezes on quest complete?

### ISSUE THREAD

**Issue by liu2z2** [coavins/mhrise-coavins-dps#18] opened 2022-02-01 05:54 UTC
**Describe the bug**
On quest completion with the mod enabled, game freezes completely until I kill it

**Steps to Reproduce**
For example:
1. Install mod v2.2.0 and dependencies
2. Configure mod with Script generated UI
3. Enter a quest hosted by someone else 
4. Game freezes immediately at the exact moment quest completes, just before the kill cam activates. The freeze can only be killed by killing the process.

**Expected behavior**
Game should not freeze when quest completes

**REFramework commit hash** (if known): `e44aa472`

**Additional context**
I admit I only tried this twice before I disabled the mod. Then the game does not freeze anymore. See the uploaded [gist](https://gist.github.com/liu2z2/07842b098b9f1542b994c7b04492aafa) for my config file.

**Comment by coavins** [comment] 2022-02-01 13:14
Thanks for including the save file, I will try to reproduce this. I haven't seen this issue yet in my testing.

Can you list any other mods that you had installed, whether or not they're using REFramework?

**Comment by coavins** [comment] 2022-02-01 14:27
I did some testing this morning and was able to get a freeze, not at quest completion but when reaching the monster after joining an ongoing quest.

I suspect these crashes might be related to the method I'm using to track ailment damage. I will investigate to see if there are other options here that would be safer to use.

**Comment by coavins** [comment] 2022-02-01 16:52
I have released v2.2.1 which rolls back the poison and damage tracking until these performance issues can be resolved.

**Comment by coavins** [comment] 2022-02-02 18:25
At the time these crashes/FPS drops were reported, I was hooking into both `activate` and `update` on `snow.enemy.EnemyConditionDamageParamBase` which has something like 8-10 instances (at least) on every large monster, and possibly small monsters too. I assumed this was the cause of the issue and removed those hooks. In 6498b40 I moved this into the enemy update function which is already being hooked in this script for other purposes.

I'm a little concerned that I'm starting to do too much work in the enemy update given that it presumably runs every frame, but so far the performance issues seem to be resolved. I feel pretty confident that it was the update hook on that condition object which was the problem.

I will stop using `getHpVital` altogether if you think there is reason to avoid it, there's probably something better on `EnemyCharacterBase` anyway that I ought to be using instead. I don't need the HP values, I just need to know whether damage against the monster should be considered productive (meaning the monster is not already dead or captured.)

Just out of curiosity, are you saying REFramework is doing this decryption behind the scenes when we call on getHpVital? I took a look at the "Monster has HP bar" script [here](https://github.com/cursey/mhrise-scripts/commits/main/monster_has_hp_bar.lua) and I don't see anything involving encryption here.

**Comment by coavins** [comment] 2022-02-02 19:05
I just published [v2.2.2](https://github.com/coavins/mhrise-coavins-dps/releases/tag/v2.2.2) which reimplements some tracking of poison and blast damage, hopefully without the same performance problems. If we continue seeing crash reports, I expect we should probably post a 2.2.3 with the removal of `getHpVital` as described above.

**Comment by coavins** [comment] 2022-02-12 18:27
I'm going to close this issue since there hasn't been any activity recently. I think the performance issues were resolved in v2.2.2.

**Closed by coavins** 2022-02-12 18:27 UTC
Labels: bug
